name: PR Tests - Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Automated tests
        run: |
          echo "Running tests..."
          sleep 5
          echo "Tests completed"
